# Generated by Django 5.2.6 on 2025-09-10 16:37

import django.db.models.deletion
import django_sendgrid_webhook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sendgrid', '0001_initial'), ('sendgrid', '0002_email_reason'), ('sendgrid', '0003_auto_20190722_1007'), ('sendgrid', '0004_alter_email_index_together'), ('sendgrid', '0005_alter_email_reason'), ('sendgrid', '0006_rename_email_content_type_object_id_sendgrid_em_content_615293_idx')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contenttypes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('email', models.CharField(max_length=512, verbose_name='addressee')),
                ('event', models.CharField(max_length=32, verbose_name='event type')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('uuid', models.CharField(db_index=True, default=django_sendgrid_webhook.models._new_uuid, max_length=64, verbose_name='reference UUID')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reason', models.TextField(default='', verbose_name='reason')),
            ],
            options={
                'index_together': {('content_type', 'object_id')},
            },
        ),
        migrations.RenameIndex(
            model_name='email',
            new_name='sendgrid_em_content_615293_idx',
            old_fields=('content_type', 'object_id'),
        ),
    ]
