# Generated by Django 2.2.3 on 2019-07-22 10:07

from django.db import migrations
from django.db.models import Index


class Migration(migrations.Migration):

    dependencies = [
        ('sendgrid', '0002_email_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=Index(fields=[set()], name='sendgrid_email_reason'),
        ),
    ]
